# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.4

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/sbin/cmake

# The command to remove a file.
RM = /usr/sbin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/saad/code/c/vulkan-renderer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/saad/code/c/vulkan-renderer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/sbin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/sbin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/saad/code/c/vulkan-renderer/CMakeFiles /home/saad/code/c/vulkan-renderer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/saad/code/c/vulkan-renderer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vulkan-renderer

# Build rule for target.
vulkan-renderer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vulkan-renderer
.PHONY : vulkan-renderer

# fast build rule for target.
vulkan-renderer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan-renderer.dir/build.make CMakeFiles/vulkan-renderer.dir/build
.PHONY : vulkan-renderer/fast

init.o: init.c.o
.PHONY : init.o

# target to build an object file
init.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan-renderer.dir/build.make CMakeFiles/vulkan-renderer.dir/init.c.o
.PHONY : init.c.o

init.i: init.c.i
.PHONY : init.i

# target to preprocess a source file
init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan-renderer.dir/build.make CMakeFiles/vulkan-renderer.dir/init.c.i
.PHONY : init.c.i

init.s: init.c.s
.PHONY : init.s

# target to generate assembly for a file
init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan-renderer.dir/build.make CMakeFiles/vulkan-renderer.dir/init.c.s
.PHONY : init.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan-renderer.dir/build.make CMakeFiles/vulkan-renderer.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan-renderer.dir/build.make CMakeFiles/vulkan-renderer.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan-renderer.dir/build.make CMakeFiles/vulkan-renderer.dir/main.c.s
.PHONY : main.c.s

window.o: window.c.o
.PHONY : window.o

# target to build an object file
window.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan-renderer.dir/build.make CMakeFiles/vulkan-renderer.dir/window.c.o
.PHONY : window.c.o

window.i: window.c.i
.PHONY : window.i

# target to preprocess a source file
window.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan-renderer.dir/build.make CMakeFiles/vulkan-renderer.dir/window.c.i
.PHONY : window.c.i

window.s: window.c.s
.PHONY : window.s

# target to generate assembly for a file
window.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan-renderer.dir/build.make CMakeFiles/vulkan-renderer.dir/window.c.s
.PHONY : window.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... vulkan-renderer"
	@echo "... init.o"
	@echo "... init.i"
	@echo "... init.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... window.o"
	@echo "... window.i"
	@echo "... window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

